Migrate to uv

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -13,7 +13,7 @@ env:
   DBT_DATASET: "ci_${{ github.event.number }}_${{ github.run_number }}_${{ github.sha }}"
   DBT_PROFILES_DIR: "."
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  POETRY_VERSION: "2.0.1"
+  UV_VERSION: "0.9.24"
 
 jobs:
   ci_pipeline:
@@ -24,24 +24,14 @@ jobs:
     steps:
       - uses: actions/checkout@v6
 
-      - uses: actions/setup-python@v6
-        id: setup-python
-
-      - name: Load cached Poetry installation
-        id: cached-poetry
-        uses: actions/cache@v5
+      - name: Install uv
+        uses: astral-sh/setup-uv@v7
         with:
-              path: /home/runner/.local
-              key: poetry-cache-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ env.POETRY_VERSION }}
+          enable-cache: true
+          version: ${{ env.UV_VERSION }}
 
-      - name: Install Poetry
-        if: steps.cached-poetry.outputs.cache-hit != 'true'
-        uses: snok/install-poetry@v1
-        with:
-              installer-parallel: true
-              version: ${{ env.POETRY_VERSION }}
-              virtualenvs-create: true
-              virtualenvs-in-project: true
+      - name: "Set up Python"
+        run: uv python install
 
       - name: 'Set up Cloud SDK'
         uses: 'google-github-actions/setup-gcloud@v3'
@@ -63,63 +53,55 @@ jobs:
           gcloud auth activate-service-account dbt-cicd@beyond-basics-$DESTINATION_BRANCH.iam.gserviceaccount.com --key-file=./service_account.json && \
           gcloud config set project beyond-basics-$DESTINATION_BRANCH
 
-      - name: Load cached venv
-        id: cached-poetry-dependencies
-        uses: actions/cache@v5
-        with:
-              path: .venv
-              key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
-
       - name: Install python packages
-        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
-        run: poetry install --no-interaction --no-ansi
+        run: uv sync
 
       - name: dbt dep
-        run: poetry run dbt deps
+        run: uv run dbt deps
 
       - name: dbt parse
-        run: poetry run dbt parse --target $DESTINATION_BRANCH
+        run: uv run dbt parse --target $DESTINATION_BRANCH
 
       - name: dbt-bouncer (manifest checks)
-        run: poetry run dbt-bouncer --only manifest_checks
+        run: uv run dbt-bouncer --only manifest_checks
 
-      - run: poetry run pytest ./tests/pytest -m no_deps -n 5
+      - run: uv run pytest ./tests/pytest -m no_deps -n 5
 
-      - run: poetry run dbt deps
+      - run: uv run dbt deps
 
       - name: dbt debug
-        run: poetry run dbt debug --target $DESTINATION_BRANCH
+        run: uv run dbt debug --target $DESTINATION_BRANCH
 
       # Create objects in BigQuery and run unit tests
       - name: dbt seed
-        run: poetry run dbt seed --target $DESTINATION_BRANCH
+        run: uv run dbt seed --target $DESTINATION_BRANCH
 
       - name: dbt run --empty
-        run : poetry run dbt run --empty --target $DESTINATION_BRANCH
+        run : uv run dbt run --empty --target $DESTINATION_BRANCH
 
       - name: dbt-bouncer (run_results checks)
-        run: poetry run dbt-bouncer --only run_results_checks
+        run: uv run dbt-bouncer --only run_results_checks
 
       - name: Run unit tests
-        run: poetry run dbt test --select "test_type:unit" --target $DESTINATION_BRANCH
+        run: uv run dbt test --select "test_type:unit" --target $DESTINATION_BRANCH
 
       # Needs to be run early in the CI pipeline to allow `dbt docs generate` to succeed (which is a dependency of pre-commit and dbt-coverage)
       - name: dbt build
-        run: poetry run dbt --warn-error build --fail-fast --full-refresh --exclude "test_type:unit" --target $DESTINATION_BRANCH
+        run: uv run dbt --warn-error build --fail-fast --full-refresh --exclude "test_type:unit" --target $DESTINATION_BRANCH
 
       - name: dbt docs generate
-        run: poetry run dbt docs generate --target $DESTINATION_BRANCH
+        run: uv run dbt docs generate --target $DESTINATION_BRANCH
 
       - name: dbt-bouncer (catalog checks)
-        run: poetry run dbt-bouncer --only catalog_checks
+        run: uv run dbt-bouncer --only catalog_checks
 
       - name: pre-commit run -a
-        run: SKIP=autoflake,dbt-compile,dbt-docs-generate poetry run pre-commit run -a
+        run: SKIP=autoflake,dbt-compile,dbt-docs-generate uv run pre-commit run -a
 
       - name: Generate docs coverage report
         id: dbt-docs-coverage-report
         run: |
-          poetry run dbt-coverage compute doc --cov-report coverage-doc.json --cov-format markdown >> coverage-doc.md
+          uv run dbt-coverage compute doc --cov-report coverage-doc.json --cov-format markdown >> coverage-doc.md
           sed -i '/# Coverage report/c\# Doc coverage report.' coverage-doc.md
 
       - uses: mshick/add-pr-comment@v2
@@ -131,7 +113,7 @@ jobs:
       - name: Generate test coverage report
         id: dbt-test-coverage-report
         run: |
-          poetry run dbt-coverage compute test --cov-report coverage-test.json --cov-format markdown >> coverage-test.md
+          uv run dbt-coverage compute test --cov-report coverage-test.json --cov-format markdown >> coverage-test.md
           sed -i '/# Coverage report/c\# Test coverage report.' coverage-test.md
 
       - uses: mshick/add-pr-comment@v2
@@ -140,23 +122,23 @@ jobs:
             message-id: dbt-test-coverage-report
             refresh-message-position: true
 
-      - run: poetry run pytest ./tests/pytest -m run_results_json -n 5
+      - run: uv run pytest ./tests/pytest -m run_results_json -n 5
 
       - name: dbt source freshness
-        run: poetry run dbt source freshness --target $DESTINATION_BRANCH || true # source freshness is allowed to fail in CI due to stale sources, the next command runs pytest on sources.json to validate the generated SQL (the prupose of this step)
+        run: uv run dbt source freshness --target $DESTINATION_BRANCH || true # source freshness is allowed to fail in CI due to stale sources, the next command runs pytest on sources.json to validate the generated SQL (the prupose of this step)
 
-      - run: poetry run pytest ./tests/pytest -m sources_json -n 5
+      - run: uv run pytest ./tests/pytest -m sources_json -n 5
 
       - name: dbt build incremental models
-        run: poetry run dbt --warn-error build --fail-fast --select config.materialized:incremental --exclude "test_type:unit" --target $DESTINATION_BRANCH
+        run: uv run dbt --warn-error build --fail-fast --select config.materialized:incremental --exclude "test_type:unit" --target $DESTINATION_BRANCH
 
       # Mart Monitor
-      - run: if [ "$DESTINATION_BRANCH" == "stg" ]; then DBT_CICD_RUN="false" poetry run dbt compile --target $DESTINATION_BRANCH --threads 64; else echo "Only runs for PRs to stg"; fi # Need manifest.json as exists during $DESTINATION_BRANCH runs and not during CI runs
+      - run: if [ "$DESTINATION_BRANCH" == "stg" ]; then DBT_CICD_RUN="false" uv run dbt compile --target $DESTINATION_BRANCH --threads 64; else echo "Only runs for PRs to stg"; fi # Need manifest.json as exists during $DESTINATION_BRANCH runs and not during CI runs
 
-      - run: if [ "$DESTINATION_BRANCH" == "stg" ]; then poetry run python ./scripts/mart_monitor_commenter.py --dbt_dataset $DBT_DATASET --pull_request_id ${{ github.event.number }} --target_branch $DESTINATION_BRANCH; else echo "Only runs for PRs to stg"; fi
+      - run: if [ "$DESTINATION_BRANCH" == "stg" ]; then uv run python ./scripts/mart_monitor_commenter.py --dbt_dataset $DBT_DATASET --pull_request_id ${{ github.event.number }} --target_branch $DESTINATION_BRANCH; else echo "Only runs for PRs to stg"; fi
 
       - name: Ensure ERD can be generated
-        run: poetry run python ./scripts/generate_marts_erd_diagram.py
+        run: uv run python ./scripts/generate_marts_erd_diagram.py
 
   dev_container:
     runs-on: ubuntu-22.04
@@ -174,9 +156,9 @@ jobs:
             echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json
             export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"cloud auth activate-service-account dbt-cicd@beyond-basics-$DESTINATION_BRANCH.iam.gserviceaccount.com --key-file=./service_account.json
             gcloud config set project beyond-basics-$DESTINATION_BRANCH
-            poetry install
-            poetry run dbt deps
-            poetry run dbt compile --target $DESTINATION_BRANCH
+            uv sync
+            uv run dbt deps
+            uv run dbt compile --target $DESTINATION_BRANCH
           env: |
             DBT_DATASET
             DBT_PROFILES_DIR
